### ISSUE TITLE
Simple Object Marker Script

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#1]
One of the frustrations of adding in new building or massive FOBs is that they do not show up on the map.

Could you please test this script and see if it is stable. If so, while you have the PBOs unpacked, we'd like to see this added so we can use it.

Thanks for all you do.

http://www.armaholic.com/page.php?id=23776

**Comment by chessmaster42** [comment]
Fixed in 22a147c35c8ce2167a57193d1d567fc46fa5c54f
