### ISSUE TITLE
MCC v17:Hotfix

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#11]
http://forums.bistudio.com/showthread.php?150909-MCC-Sandbox-3-Dynamic-mission-creating-tool-for-ArmA-3&p=2618148&viewfull=1#post2618148

Can we attempt to adopt this in the next few hours, before the event?

**Comment by chessmaster42** [comment]
Done but not pushed out to the repo yet.

**Comment by chessmaster42** [comment]
Done in 0b4a18643a316723c3dec0402151506aaccd8034
