### ISSUE TITLE
Psycho Wounding: Severly Wounded Health

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#13]
We need to make the player, so long as he is laying "wounded", and not fighting: much heartier (I'd even say invincible if he stays on his back).

**Comment by chessmaster42** [comment]
Yeah I've been tinkering with this one. I'll need to do some testing with some live bodies instead of AI to really see if it's working though. Worst case I can just set it so you're invincible while down but I really don't like the idea of that.

**Comment by chessmaster42** [comment]
Fixed in 981f7a5214d623659b9f10aae2b9978f6dbf3bba

I currently have players invincible until you leave the "passive" state by firing your weapon. With more testing and tweaking I'll get it working with reduced damage but I think this will be okay for the time being.
