### ISSUE TITLE
Gear Loadout

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#15]
Something broke, and you no longer have your past gear on death anymore

**Comment by chessmaster42** [comment]
This is a setting inside of MCC but in v18 it was changed to default to off. I have changed the default to on for us and it will be in the next build.

**Comment by chessmaster42** [comment]
So far I can't find a non-buggy way to enable this by default. But once the mission is loaded in the server whoever is logged into MCC just needs to click on Mission Settings and down at the bottom is the drop-down to enable gear saving.

Closing as I can't find any way to change this right now but if I do I will re-open and post details.
