### ISSUE TITLE
Psycho Wounding: First Aid When Down

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#18]
Add the ability to give yourself First Aid when you are Downed, so that you can increase (double?) your bleed-out time.

Also, if you are the Medic, you can crawl to safety and get yourself UP.

**Comment by chessmaster42** [comment]
This is going to be tricky but doable since the down state disables all functional UI and interaction. I'll have to look into a way to add a custom context menu for just being in agony. More design/ideas certainly welcome here.

**Comment by chessmaster42** [comment]
Right now the plan is to have a "Bandage" option that will consume a first aid kit and give an extra 60 seconds to your bleed out timer. Not sure yet what the best way is to implement something for the medic though. Perhaps an adrenaline shot or something that brings you up temporarily for 30 seconds or something.

**Comment by chessmaster42** [comment]
Second part is complete in e62874d15912b1224d3559b5d7313e31bed970c1

Still working on config+design for non-medic bandaging while down
