### ISSUE TITLE
Pearson Wounding: Latest Issues

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#25]
• For the Medic, They are not healing Players 100%.

• We need a way for the medic to get himself up in combat. We have agreed this'll be a KeyCombo, and we should try Control+E+R.

• Message Should come up (in yellow) at the TOP position of a Medic's Screen, telling them to press Control+E+R to start to Patch themselves up.

**Comment by chessmaster42** [comment]
First one is fixed in c9c41c20186b8c016e41187c4ecbc9f790fc4e6a

Working on design to handle the other two. Don't have an estimate yet when it will be ready though.

**Comment by chessmaster42** [comment]
Completed in e62874d15912b1224d3559b5d7313e31bed970c1

Not going to implement message, will be part of readme later
