### ISSUE TITLE
Death upon respawn

### ISSUE THREAD

**Issue by MiC17** [DogsoftheState/mcc_sandbox#29]
Instead of the previous Death loop you now die exactly once after respawning, then it's fine.

**Comment by chessmaster42** [comment]
Odd but interesting. I have a guess why this is happening but I don't think I'll be able to dig in to fix it until Sunday most likely. At least it's consistent and only happens once.

**Comment by chessmaster42** [comment]
Closing as all of wounding system bugs should now be made in the new repository for my wounding system: https://github.com/chessmaster42/cws_injury
