### ISSUE TITLE
Class List Garbled/Ommissions

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#4]
The Arma2 Map Pack ruins the class lists some. You have already seen this by seeing all the duplicate [ West ] class containers in the 3D Editor. That is a minor inconvenience. 

However, when trying to place SOME assets they simply are not there. This bug is repeatable. 

With @A3MP enabled, go to 3D Editor > NATO [ WEST ] > Objects [ Training ] > ( and look for any of the Pop-Up, or Moving Targets)... They are simply not there.

A great many MORE things than just these are missing. Removing the Arma2 Map Pack fixes the issue. I've disabled the mod from my startup properties and see all the objects/classes as intended. 

Please look into what we might do to fix this. I am hoping it's just a file or two that needs to be edited.

**Comment by chessmaster42** [comment]
Is this happening when on Altis or Stratis? If I remember right this was only on the map pack maps.

**Comment by chessmaster42** [comment]
Apparently fixed in MCC v17
