### ISSUE TITLE
Task Force Radio Compatibibility

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#5]
Adding this to the init.sqf make it so that Fire Team Leaders no longer spawn with the long range pack. I feel this is beneficial as we don't always have 2 teams, and don't always need long range.

tf_no_auto_long_range_radio = true;

**Comment by chessmaster42** [comment]
This is already there - https://github.com/chessmaster42/mcc_sandbox/blob/master/mcc_sandbox.altis/init.sqf#L82
