### ISSUE TITLE
Bombs and TV Radio

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#6]
Bombs from Bombers are useless.

You have to be VERY good at dive bombing and you have no way of knowing if your bomb hit unless you always have ground support.

We are looking at wanting to install this script. 

http://www.armaholic.com/page.php?id=24571

It'll make bombers have purpose.

**Comment by chessmaster42** [comment]
Will be added in the next build

**Comment by chessmaster42** [comment]
Done in 7d2d271e6929d6eff530b5fd3d853a8dbd730390
