### ISSUE TITLE
VAS Has updated

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#8]
While MCC has matured, the VAS has as well, but they have not together.

http://forums.bistudio.com/showthread.php?149077-Virtual-Ammobox-System-(VAS)

As such, to see a more responsive VAS, we'd like to see the latest version packaged. It also should help us filter larger lists better.

**Comment by chessmaster42** [comment]
Will be updated from 2.2 (packed with MCC) to 2.4 which is the latest in the next build

**Comment by chessmaster42** [comment]
Done in 7d2d271e6929d6eff530b5fd3d853a8dbd730390
