### ISSUE TITLE
MCC hates servers

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#9]
The latest version of MCC has a memory leak, or something similar, that makes missions (and making them feel dynamic) nearly unplayable after 15 min.

http://forums.bistudio.com/showthread.php?150909-MCC-Sandbox-3-Dynamic-mission-creating-tool-for-ArmA-3&p=2616489&viewfull=1#post2616489

This has been confirmed by multiple parties. Those who take the time to roll-back experience NO issues. It is our hope that with this repository, we can roll back to 15 (or 16), and make the other, changes (read:Issues) I have requested. In this way we can have our dynamic missions back, and be able to do something large as a clan this weekend.

**Comment by chessmaster42** [comment]
Closed as this is no longer an issue with MCC v18

**Comment by FUTUREMCC** [comment]
What version of MCC are you guy running here? I dont see the form coming from the original place we hold.
